name: "Run remark-lint with reviewdog"
description: "🐶 Run remark-lint with reviewdog on pull requests to improve code review experience."
author: "prologic"
inputs:
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  remark_args:
    description: "Additional remark-lint input arguments."
    required: false
    # NOTE: The actual default values is '--use=remark-preset-lint-recommended' but it is
    # only applied programmatically when no input or config file is found.
    default: ""
  install_deps:
    description: "Install dependencies."
    required: false
    default: "true"
  # Reviewdog related inputs
  github_token:
    description: "GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}
  tool_name:
    description: "Tool name to use for reviewdog reporter."
    required: false
    default: "remark-lint"
  level:
    description: "Report level for reviewdog [info, warning, error]."
    required: false
    default: "error"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check, github-pr-review, github-check]."
    required: false
    default: "github-pr-check"
  filter_mode:
    description: "Filtering mode for the reviewdog command [added, diff_context, file, nofilter]."
    required: false
    default: "added"
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog.
      Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: "Deprecated, use `fail_level` instead. Exit code for reviewdog when errors are found [true, false]."
    deprecationMessage: Deprecated, use `fail_level` instead.
    required: false
    default: "false"
  reviewdog_flags:
    description: "Additional reviewdog flags."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_REMARK_ARGS: ${{ inputs.remark_args }}
        INPUT_INSTALL_DEPS: ${{ inputs.install_deps }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "zoom-in"
  color: "purple"
